# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3cA9S864cC2oTYsWHBci7pcFl3dG9Dg
"""

import streamlit as st

st.title("Hansito Store")
st.header("encabezado")
st.subheader("sub encabezado")
st.write("introduccion")